name: Generate PDF

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy-gh-page:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y libpango-1.0-0 libpangoft2-1.0-0 libpangocairo-1.0-0 libcairo2
            pip install weasyprint markdown markdown2 pdfkit

      - name: Generate PDF
        run: python .github/scripts/md_to_pdf.py

      - name: Add cache buster to README link
        run: |
          TIMESTAMP=$(date +%s)
          sed -i "s|Toufiqur_Chowdhury_CV.pdf|Toufiqur_Chowdhury_CV.pdf?v=${TIMESTAMP}|g" README.md

      - name: Prepare index.md
        run: cp README.md index.md

      - name: Prepare LICENSE
        run: cp LICENSE LICENSE.md

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Copy assets to _site
        run: cp -r assets ./_site/ || echo "No assets directory found to copy"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
