on:
  push:
    branches:
      - main
    paths-ignore:
      - Toufiqur_Chowdhury_CV.pdf  # ignore when only this file changes

  workflow_dispatch:  # still allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install markdown weasyprint pygments

      - name: Convert README.md to PDF
        run: |
          python .github/scripts/md_to_pdf.py

      - name: Commit PDF
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Toufiqur_Chowdhury_CV.pdf
          git commit -m "Auto-generate PDF from README"
          git push
